### ISSUE TITLE
AmcatAPI raises a 405 error on connection attempt

### ISSUE THREAD

**Issue by bobvdvelde** [amcat/amcatclient#6]
`conn = AmcatAPI('http://amcat.vu.nl','username','password') #obviously with real username and password.`

raises:

APIError: [Errno 405] Request u'https://amcat.nl/api/v4/get_token' returned code 405, expected 200. Response written to /var/folders/6n/xzg_cy2j5pd1181n04s8m0kh0000gn/T/tmpic7kIn.txt: u'https://amcat.nl/api/v4/get_token': None; None

Or is this just me? 

Did the endpoint change (i.e. no longer accepts post requests? )

**Comment by vanatteveldt** [comment]
You need to use https://amcat.vu.nl (note the https). Does that work?

**Comment by bobvdvelde** [comment]
It does! My previous attempts had failed because the certificate throws and error for 'https://amcat.vu.nl' (instead of 'https://amcat.nl'). You may want to change the readme to reflect the `https` part ;-)

Thanks for the quick solution.

**Comment by vanatteveldt** [comment]
O wait, does https://amcat.nl not work? I'm pretty sure that's what I use...?

**Comment by bobvdvelde** [comment]
Sorry for the mix-up, https://amcat.nl works and https://amcat.vu.nl does not. 

Perhaps unsurprisingly, it's the VU part. 

This is interesting, as password-reset emails point you to the amcat.vu.nl subdomain, which my browser tells me is unsafe. If these would send me to https://amcat.nl , this issue would probably be solved. 

Sorry for mucking about.
